/** Clubhouse Almanac content model: focused coaching problems, clear tiers, and shareable update notes. */
export type Tier = "starter" | "deep";
export type Article = { slug: string; tier: Tier; tags: string[]; title: string; description: string; date: string; readTime: string; intro: string; sections: { heading: string; copy: string[] }[] };
export type Update = { slug: string; type: "product update" | "development note"; date: string; title: string; summary: string; details: string[] };

export const topicTags = [
  "Coaching as a Profession",
  "Running a Coaching Business That Lasts",
  "The Coach-Parent Relationship, Done Properly",
  "Player Development With a System Behind It",
];

export const topicDescriptions: Record<string, string> = {
  "Coaching as a Profession": "For coaches still developing their judgement, reflective practice and standards, not looking for a quick drill.",
  "Running a Coaching Business That Lasts": "For coaches thinking in seasons and years, where structure and continuity matter more than short-term volume.",
  "The Coach-Parent Relationship, Done Properly": "For coaches who believe parents deserve a clear, professional account of progress and trust.",
  "Player Development With a System Behind It": "For coaches who know development needs a record, a next step and enough structure to prove what happened.",
};

export const articles: Article[] = [
  { slug: "why-most-coaching-plans-fall-apart-by-week-three", tier: "starter", tags: ["Running a Coaching Business That Lasts", "Coaching as a Profession"], title: "Why most coaching plans fall apart by week three", description: "A practical look at why a promising tennis coaching plan loses momentum, and one way to keep the useful parts in play.", date: "26 August 2026", readTime: "4 min read", intro: "A plan is not a promise that every session will run perfectly. It is a way of deciding what matters when the week gets busy.", sections: [{ heading: "The plan was never the problem", copy: ["Most plans begin with good intention: a clear technical theme, a sequence of sessions, perhaps a parent update in mind. Then a cancellation arrives, a player changes group, the weather turns, and the useful bits are scattered across a diary, a notebook and a message thread.", "By week three, the plan has not been abandoned because the coach stopped caring. It has been abandoned because it had nowhere resilient to live."] }, { heading: "Make the next decision easier", copy: ["A practical plan should answer three things quickly: what the player is working on, what changed last time, and what the next session needs. If those answers take ten minutes to find, the plan is already under pressure.", "Keep the record short enough to use on a busy Tuesday. The ambition is not perfect administration. It is a clearer next move."] }] },
  { slug: "one-question-before-every-tennis-session", tier: "starter", tags: ["Player Development With a System Behind It", "Coaching as a Profession"], title: "The one question to ask before every session", description: "A useful pre-session question for tennis coaches who want each player to leave with a clearer next step.", date: "24 August 2026", readTime: "3 min read", intro: "Before the balls come out, there is one question worth asking: what would make this session genuinely useful for this player today?", sections: [{ heading: "Useful is more precise than busy", copy: ["A full basket, a lively group and a hard-working player can all make a session feel productive. But activity is not always direction.", "The question forces a coach to look at the player in front of them rather than the session they had planned in the car park."] }, { heading: "Let the answer be small", copy: ["The answer may be a movement pattern, a choice under pressure, or a better way to reset after an error. It does not need to be grand to matter.", "When one useful outcome is clear, the exercises, language and feedback have a better chance of pulling in the same direction."] }] },
  { slug: "what-tennis-parents-actually-want-to-hear", tier: "starter", tags: ["The Coach-Parent Relationship, Done Properly"], title: "What tennis parents actually want to hear", description: "A more constructive way to communicate player progress to tennis parents without turning every conversation into a report.", date: "21 August 2026", readTime: "5 min read", intro: "Most parents are not asking for a technical lecture. They are asking whether their child is seen, supported and moving forward.", sections: [{ heading: "Start with what is changing", copy: ["A useful update makes progress visible. It can name a small improvement, a current challenge and the next area of attention without making a parent feel like an observer at the edge of the process.", "The most reassuring communication is specific and calm. It shows that the coach has a view of the player beyond today’s score."] }, { heading: "Keep the relationship human", copy: ["Parents do not need constant contact. They need the right contact at the right time, in language they can understand.", "A short, thoughtful note can do more for trust than a long explanation delivered after uncertainty has built up."] }] },
  { slug: "tracking-player-development-or-remembering-it", tier: "deep", tags: ["Player Development With a System Behind It", "Coaching as a Profession"], title: "Are you actually tracking player development, or just remembering it?", description: "A diagnostic guide for coaches who want a reliable picture of player development between sessions, programmes and conversations.", date: "26 August 2026", readTime: "8 min read", intro: "Remembering the important things is a strength. Relying on memory for every important thing is a risk that grows with every player and every week.", sections: [{ heading: "Memory is selective by design", copy: ["Good coaches notice a great deal in real time: the serve that changed, the reaction after a mistake, the parent conversation that needs a follow-up. The difficulty is not awareness. It is carrying that awareness accurately into the next session.", "When development lives only in memory, the loudest recent moment can eclipse the quieter pattern that matters more."] }, { heading: "A player story is more than a note", copy: ["A useful record connects three points: what the player was working on, what happened, and what comes next. That is enough to turn individual observations into a developing story.", "The system should support professional judgement, not replace it with boxes to tick. The best record is one a coach trusts enough to use before the next conversation."] }, { heading: "A short diagnostic", copy: ["Could you explain a player’s current priority without opening three different apps? Could another coach step in and understand the next useful session? Could you show a parent how progress is being noticed? If those answers feel uncertain, the work may be happening, but it is not yet being held."] }] },
  { slug: "hidden-cost-running-coaching-business-from-memory", tier: "deep", tags: ["Running a Coaching Business That Lasts", "Coaching as a Profession"], title: "The hidden cost of running your coaching business from memory", description: "A diagnostic read for tennis coaches who want to protect coaching attention from the quiet cost of scattered admin.", date: "23 August 2026", readTime: "7 min read", intro: "The cost of working from memory is rarely one dramatic mistake. It is the accumulation of small retrieval jobs that quietly take your attention away from the court.", sections: [{ heading: "The work between the work", copy: ["The messages, reschedules, notes and reminders are not beneath coaching. They are part of the service a player and parent experience. The problem comes when every useful detail has to be reconstructed from a different place.", "That reconstruction is invisible labour. It makes a coach feel busy even when the day has contained less coaching than it should."] }, { heading: "Clarity is a business asset", copy: ["When the week is visible and player context can be found quickly, decisions become calmer. Updates become more timely. A coach has more space to prepare rather than chase.", "The aim is not a more complicated operation. It is a more dependable one."] }] },
  { slug: "what-high-performing-coaching-session-structure-looks-like", tier: "deep", tags: ["Player Development With a System Behind It", "Coaching as a Profession"], title: "What a high-performing coaching session structure actually looks like", description: "A practical framework for creating tennis coaching sessions that connect player context, deliberate practice and a clear next step.", date: "19 August 2026", readTime: "9 min read", intro: "A high-performing session is not a list of impressive drills. It is a deliberate sequence that helps one player do something better than they could at the start.", sections: [{ heading: "Begin with context", copy: ["The session needs a point of entry: an existing player priority, a recent observation, a competition coming up, or a confidence pattern worth addressing. Context gives the work a reason.", "Without it, even good activities can feel like isolated entertainment."] }, { heading: "Build a progression, not a playlist", copy: ["A sequence should move the player from a recognisable starting point toward a challenge where the intended learning has to be used. The middle is not there to fill time; it is there to create useful repetition and feedback.", "This is why a plan needs room for judgement. The same session structure can flex when the player needs a different question, a shorter task or a more demanding constraint."] }, { heading: "Finish with the next move", copy: ["The session ends when the player and coach can name what has changed and what to carry into the next opportunity. That could be a technical cue, a tactical choice or a practice focus.", "The next move matters because it turns one session into part of a player story rather than a good hour that disappears when the court is swept."] }] },
];

export const updates: Update[] = [
  { slug: "building-a-steadier-coaching-week", type: "development note", date: "26 August 2026", title: "Building a steadier coaching week", summary: "A short note on the product direction: give the people, plans and small useful details of coaching one professional and functional place to live.", details: ["CG Tennis OS™ is being shaped around a simple operating belief: the best software makes a coach more available to the people in front of them, not more available to a dashboard.", "This companion site will share the small decisions, practical improvements and development thinking behind the system as it takes shape."] },
  { slug: "a-place-for-player-stories", type: "product update", date: "18 August 2026", title: "A clearer place for player stories", summary: "The product is being refined around the context a coach needs before the next conversation and the next session.", details: ["A player record should hold more than a result or a quick note. It should make the player’s current work visible and help a coach find the next useful question.", "The goal is not to create more admin. It is to let the note from court-side retain its meaning when it is needed again."] },
  { slug: "keeping-parent-updates-useful", type: "development note", date: "08 August 2026", title: "Keeping parent updates useful", summary: "A look at why the right update matters more than constant contact, and how the system is being designed around that principle.", details: ["Parents want to know that their child is seen and making progress. They rarely need a technical report after every session.", "We are keeping the communication side of CG Tennis OS™ focused on timely, clear and human updates that build trust without creating another daily task."] },
];

export const getArticle = (slug: string) => articles.find((article) => article.slug === slug);
export const getUpdate = (slug: string) => updates.find((update) => update.slug === slug);
export const relatedTo = (article: Article) => articles.filter((item) => item.slug !== article.slug && item.tier === article.tier && item.tags.some((tag) => article.tags.includes(tag))).slice(0, 3);
