/** Clubhouse Almanac supporting pages: personal authority, clear system explanation, an SEO library and public development notes. */
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, Clock3, Download, Mail, MoveRight, Search } from "lucide-react";
import { Link, useRoute } from "wouter";
import { ArticleCard } from "@/components/ArticleCard";
import { topicDescriptions, topicTags, type Article, type Update } from "@/lib/content";

const CONTENT_API = import.meta.env.VITE_CONTENT_API_BASE || "https://api.cgtennisos.com";
const SITE_URL = "https://cgtennisos.info";
const topicKeyToLabel: Record<string, string> = { coaching_craft: "Coaching as a Profession", business_longevity: "Running a Coaching Business That Lasts", parent_relationship: "The Coach-Parent Relationship, Done Properly", development_systems: "Player Development With a System Behind It", coaching_systems_operations: "Coaching Systems & Operations" };
function usePageMetadata({ title, description, path, schema }: { title: string; description: string; path: string; schema?: Record<string, unknown> }) {
  const schemaJson = schema ? JSON.stringify(schema) : "";
  useEffect(() => {
    document.title = title;
    let descriptionTag = document.querySelector('meta[name="description"]');
    if (!descriptionTag) { descriptionTag = document.createElement("meta"); descriptionTag.setAttribute("name", "description"); document.head.appendChild(descriptionTag); }
    descriptionTag.setAttribute("content", description);
    let canonical = document.querySelector('link[rel="canonical"]');
    if (!canonical) { canonical = document.createElement("link"); canonical.setAttribute("rel", "canonical"); document.head.appendChild(canonical); }
    canonical.setAttribute("href", `${SITE_URL}${path}`);
    let structuredData = document.getElementById("cg-structured-data");
    if (schemaJson) {
      if (!structuredData) { structuredData = document.createElement("script"); structuredData.id = "cg-structured-data"; structuredData.setAttribute("type", "application/ld+json"); document.head.appendChild(structuredData); }
      structuredData.textContent = schemaJson;
    } else if (structuredData) structuredData.remove();
    return () => { if (structuredData) structuredData.remove(); };
  }, [title, description, path, schemaJson]);
}
function articleFromApi(item: { slug: string; tier?: string | null; topic_tag?: string | null; title: string; meta_description?: string; published_at?: string; body?: string }) {
  const lines = String(item.body || "").split(/\r?\n/);
  const sections: Article["sections"] = []; const introLines: string[] = []; let heading = ""; let copy: string[] = [];
  const push = () => { if (heading) sections.push({ heading, copy: copy.filter(Boolean) }); heading = ""; copy = []; };
  for (const line of lines) { if (line.startsWith("## ")) { push(); heading = line.slice(3).trim(); } else if (line.trim() && !line.startsWith("# ")) { const value = line.replace(/^[-*] /, "").trim(); if (heading) copy.push(value); else introLines.push(value); } }
  push();
  const intro = introLines.join(" ").trim();
  const allCopy = [intro, ...sections.flatMap(section => section.copy)].filter(Boolean);
  return { slug: item.slug, tier: item.tier === "deep_dive" ? ("deep" as const) : ("starter" as const), tags: item.topic_tag ? [topicKeyToLabel[item.topic_tag] || item.topic_tag] : [], title: item.title, description: item.meta_description || "", date: item.published_at ? new Intl.DateTimeFormat("en-GB", { dateStyle: "long" }).format(new Date(item.published_at)) : "", readTime: `${Math.max(1, Math.ceil(allCopy.join(" ").split(/\s+/).length / 220))} min read`, intro, sections };
}
async function fetchPublishedArticles(): Promise<Article[]> { const response = await fetch(`${CONTENT_API}/api/content?type=article&status=published`); if (!response.ok) throw new Error("Published articles unavailable"); return (await response.json()).map(articleFromApi) as Article[]; }
async function fetchPublishedUpdates() { const response = await fetch(`${CONTENT_API}/api/content?type=product_update&status=published`); if (!response.ok) throw new Error("Published updates unavailable"); return await response.json(); }

const Mark = ({ number, label }: { number: string; label: string }) => <aside className="section-mark"><b>{number}</b><i /><span>{label}</span></aside>;

export function About() { return <><section className="page-hero about-hero"><div className="frame page-hero-grid"><div><p className="eyebrow">About Caroline</p><h1>Thirty years <i>on court.</i></h1><p>Caroline Gossage has spent three decades coaching tennis, working with players, parents and fellow coaches at every stage of the game.</p></div><div className="portrait-frame"><span>Coach.<br />Author.<br />Builder.</span><img src="/assets/about-caroline.webp" alt="Illustrated portrait of Caroline Gossage on a tennis court" /></div></div></section><section className="editorial-section"><div className="narrow editorial-grid"><Mark number="01" label="The foundation" /><div><p className="lead">CG Tennis OS™ is built on that experience. A system shaped by someone who has run thousands of sessions, not designed by someone who has run none.</p></div></div></section><section className="editorial-section sand"><div className="narrow editorial-grid"><Mark number="02" label="Why she wrote the book" /><div><h2>What actually separates coaches who develop players consistently from those who do not?</h2><p>After years of watching good coaches undersell themselves, and average coaches coast on charisma, Caroline wrote <i>Are You a High-Performing Coach?</i> to ask a simple, uncomfortable question.</p><p>The answer was not more qualifications. It was structure, language, and habits most coaching never teaches.</p><a className="text-link" href="https://www.amazon.co.uk/dp/0992666104" target="_blank" rel="noreferrer">Read the book on Amazon UK <ArrowUpRight size={16} /></a></div></div></section><section className="editorial-section"><div className="narrow editorial-grid"><Mark number="03" label="Why she built it" /><div><h2>The book gave coaches the thinking. CG Tennis OS™ gives them somewhere to put it into practice.</h2><p>A system for planning, tracking, and communicating, built the way real coaching actually works, not the way software assumes it should.</p><p>Caroline still coaches. Everything in CG Tennis OS™ is tested against that reality first.</p><Link href="/cg-tennis-os" className="button-secondary">Explore CG Tennis OS™ <MoveRight size={17} /></Link></div></div></section><section className="philosophy-band"><div className="frame philosophy-grid"><div><p className="eyebrow peach">The philosophy</p><h2>Coaching Intelligence.<br /><i>Human Wisdom.</i></h2></div><p>Not decoration. This is the whole philosophy. Good coaching software sharpens a coach’s judgement. It doesn’t replace it.</p><a href="https://cgtennisos.com" target="_blank" rel="noreferrer" className="button-primary">Start your free trial <ArrowUpRight size={17} /></a></div></section></>; }

export function Book() { return <><section className="book-hero"><div className="frame book-grid"><div className="book-frame"><img src="/assets/book-cover.webp" alt="Are You a High-Performing Coach? book cover by Caroline Gossage" /><span>The thinking<br />behind the system.</span></div><div><p className="eyebrow">The book</p><h1>Are You a <i>High-Performing Coach?</i></h1><p className="book-subtitle">Strategies for an outstanding sports coaching career.</p><p>For coaches who want to understand what consistently develops players. It goes beyond charisma, qualifications and a good session on a good day.</p><div className="book-actions"><a href="https://www.amazon.co.uk/dp/0992666104" target="_blank" rel="noreferrer" className="button-primary">Find the book on Amazon UK <ArrowUpRight size={17} /></a><a href="mailto:hello@cgtennisacademies.com?subject=Book%20excerpt%20request" className="text-link">Request the opening excerpt <Download size={16} /></a></div></div></div></section><section className="editorial-section"><div className="narrow editorial-grid"><Mark number="01" label="The question" /><div><p className="lead">What actually separates coaches who develop players consistently from those who do not?</p><p>Caroline’s book asks the question that is easy to avoid when the day is full: are the habits, language and structures around your coaching helping good work travel from one session to the next?</p></div></div></section><section className="chapters"><div className="frame chapters-grid"><div><p className="eyebrow">Inside the book</p><h2>Practical thinking for a coaching career that can <i>last.</i></h2></div><div>{["Seeing the coach behind the session.", "Developing a coaching language players can use.", "Making structure support, rather than flatten, your judgement.", "Building a service parents can understand and trust."].map((text, index) => <div key={text}><span>0{index + 1}</span><p>{text}</p></div>)}</div></div></section><section className="dark-close"><div className="frame"><p className="eyebrow peach">From thought to practice</p><h2>The book gave coaches the thinking.<br /><i>CG Tennis OS™ gives it somewhere to live.</i></h2><Link href="/cg-tennis-os" className="text-link light-link">Explore the system <MoveRight size={17} /></Link></div></section></>; }

export function Insights() {
  const [tier, setTier] = useState<"all" | "starter" | "deep">("all");
  const [tag, setTag] = useState("All topics");
  const [liveArticles, setLiveArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  useEffect(() => { fetchPublishedArticles().then(setLiveArticles).catch(() => setLoadError(true)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => liveArticles.filter(a => (tier === "all" || a.tier === tier) && (tag === "All topics" || a.tags.includes(tag))), [tag, tier, liveArticles]);
  const topicDescription = tag === "All topics" ? "Choose the coaching question that already matters to you. The labels are deliberately specific." : topicDescriptions[tag];
  return <><section className="insights-hero"><div className="frame two-col"><div><p className="eyebrow peach">Insights</p><h1>Clearer thinking,<br /><i>better coaching.</i></h1></div><p>Practical thinking on coaching, systems and player development from Caroline and CG Tennis OS™.</p></div></section><section className="tier-section"><div className="frame tier-grid"><article><span>01</span><p className="eyebrow">Starter reads</p><h2>Useful without needing to know us first.</h2><p>Short, standalone pieces for a real coaching question. No product pitch in the middle of the thinking.</p></article><article><span>02</span><p className="eyebrow">Deep dives</p><h2>For when you are ready to look more closely.</h2><p>Longer diagnostic reads about the systems, habits and decisions that hold a coaching practice together.</p></article></div></section><section className="insights-assessment"><div className="frame insights-assessment-grid"><figure className="insights-guide"><span>FIELD GUIDE<br />NOTE 06</span><img src="/assets/courttoon-netty_8532c5a4.svg" alt="Netty CourtToon field-guide figure" /></figure><div><p className="eyebrow peach">A practical diagnostic</p><h2>Not sure where to <i>start looking?</i></h2><p>The Coach Operating Readiness Index™ is a five-minute, six-dimension assessment of how the work around your coaching currently runs.</p></div><Link href="/coach-readiness" className="button-secondary">Take the Readiness Index <ArrowUpRight size={17} /></Link></div></section><section className="library"><div className="frame"><div className="library-head"><div><p className="eyebrow">Find a useful answer</p><h2>The coaching library</h2></div><span>{loading ? "Loading published reads" : `${filtered.length} considered reads`}</span></div><div className="filters"><div><b><Search size={14} /> Tier</b>{(["all", "starter", "deep"] as const).map(item => <button className={tier === item ? "active" : ""} key={item} onClick={() => setTier(item)}>{item === "all" ? "All reading" : item === "starter" ? "Starter reads" : "Deep dives"}</button>)}</div><div><b>Topic</b>{["All topics", ...topicTags].map(item => <button className={tag === item ? "active" : ""} key={item} onClick={() => setTag(item)}>{item}</button>)}</div><p className="filter-note">{topicDescription}</p></div>{loadError ? <p className="content-state content-error">Published insights are temporarily unavailable. Please try again shortly.</p> : !loading && filtered.length === 0 ? <p className="content-state content-empty">No published reads yet. Please check back soon.</p> : <div className="article-grid">{filtered.map(article => <ArticleCard article={article} key={article.slug} />)}</div>}</div></section></>;
}

export function ArticlePage() {
  const [, params] = useRoute("/insights/:slug");
  const slug = params?.slug || "";
  const [article, setArticle] = useState<Article | null>(null);
  const [related, setRelated] = useState<Article[]>([]);
  const [articleError, setArticleError] = useState(false);
  useEffect(() => { setArticle(null); setRelated([]); setArticleError(false); fetch(`${CONTENT_API}/api/content/${slug}?type=article`).then(response => response.ok ? response.json() : null).then(item => { if (!item) { setArticleError(true); return; } const next = articleFromApi(item); setArticle(next); return fetchPublishedArticles().then(items => setRelated(items.filter(candidate => candidate.slug !== next.slug && candidate.tier === next.tier && candidate.tags.some(tag => next.tags.includes(tag))).slice(0, 3))); }).catch(() => setArticleError(true)); }, [slug]);
  usePageMetadata({ title: article ? `${article.title} | CG Tennis OS™` : "Insight | CG Tennis OS™", description: article?.description || "Practical coaching insight from Caroline Gossage and CG Tennis OS™.", path: `/insights/${slug}`, schema: article ? { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: article.date, author: { "@type": "Person", name: "Caroline Gossage" }, publisher: { "@type": "Organization", name: "CG Tennis OS™", url: SITE_URL }, mainEntityOfPage: `${SITE_URL}/insights/${slug}` } : undefined });
  if (!article) return articleError ? <NotFound /> : <section className="not-found"><p className="eyebrow">Loading insight</p><h1>Finding the useful detail.</h1></section>;
  return <><article className="article-page"><header className="narrow article-head"><Link href="/insights" className="back"><ArrowLeft size={16} /> All insights</Link><div className="article-meta"><span className={`tier-pill ${article.tier}`}>{article.tier === "starter" ? "Starter read" : "Deep dive"}</span><span>{article.date}</span><span><Clock3 size={14} /> {article.readTime}</span></div><h1>{article.title}</h1><p className="dek">{article.description}</p><div className="byline"><b>CG</b><span>Written by <strong>Caroline Gossage</strong></span></div></header><div className="article-body"><aside className="coaching-margin"><span>COURT-SIDE NOTE</span><i /><p>{article.tier === "deep" ? "Look for the pattern before you reach for the fix." : "The useful question is usually more valuable than the clever answer."}</p></aside><p className="article-intro">{article.intro}</p>{article.sections.map(section => <section key={section.heading}><h2>{section.heading}</h2>{section.copy.map(copy => <p key={copy}>{copy}</p>)}</section>)}{article.tier === "deep" && <aside className="article-cta"><p className="eyebrow peach">When the thinking is ready</p><h3>See how CG Tennis OS™ handles this.</h3><p>Give player stories, session plans and useful updates one home, so your coaching judgement has more room to work.</p><a href="https://cgtennisos.com" target="_blank" rel="noreferrer" className="button-primary">Start your free trial <ArrowUpRight size={17} /></a></aside>}</div></article>{related.length > 0 && <section className="related"><div className="frame"><p className="eyebrow">Stay with the thread</p><h2>Related {article.tier === "deep" ? "deep dives" : "starter reads"}</h2><div className="article-grid">{related.map(item => <ArticleCard article={item} key={item.slug} />)}</div></div></section>}</>;
}

export function Updates() { return <Changelog />; }

export function Changelog() {
  const [liveUpdates, setLiveUpdates] = useState<Update[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  useEffect(() => { fetchPublishedUpdates().then(setLiveUpdates).catch(() => setLoadError(true)).finally(() => setLoading(false)); }, []);
  usePageMetadata({ title: "Changelog | CG Tennis OS™", description: "Product notes and development progress from CG Tennis OS™.", path: "/changelog" });
  return <><section className="updates-hero"><div className="frame two-col"><div><p className="eyebrow peach">Changelog</p><h1>Follow the work <i>as it develops.</i></h1></div><p>Product notes and development progress from CG Tennis OS™. This is the technical record, kept separate from the coaching Insights library.</p></div></section><section className="updates-list"><div className="frame updates-grid"><aside className="updates-margin"><span>CG / OS</span><i /><p>BUILD LOG</p><img src="/assets/courttoon-netty_8532c5a4.svg" alt="Netty CourtToon guide" /></aside><div><div className="updates-intro"><p className="eyebrow">A working system, openly shaped</p><h2>Small improvements should be visible.</h2></div>{loadError ? <p className="content-state content-error">Published product updates are temporarily unavailable. Please try again shortly.</p> : !loading && liveUpdates.length === 0 ? <p className="content-state content-empty">No published product updates yet. Please check back soon.</p> : liveUpdates.map((update, index) => <Link href={`/changelog/${update.slug}`} key={update.slug} className="update-row"><span>0{index + 1}</span><div><p className="eyebrow">Product update · {update.published_at ? new Intl.DateTimeFormat("en-GB", { dateStyle: "long" }).format(new Date(update.published_at)) : update.date}</p><h3>{update.title}</h3><p>{update.summary || update.meta_description}</p></div><ArrowUpRight size={22} /></Link>)}</div></div></section></>;
}

export function UpdatePage() { const [, params] = useRoute("/updates/:slug"); const [, changelogParams] = useRoute("/changelog/:slug"); const slug = params?.slug || changelogParams?.slug || ""; const [update, setUpdate] = useState<Update | null>(null); const [updateError, setUpdateError] = useState(false); useEffect(() => { setUpdate(null); setUpdateError(false); fetch(`${CONTENT_API}/api/content/${slug}?type=product_update`).then(response => response.ok ? response.json() : null).then(item => { if (item?.type === "product_update") setUpdate({ slug: item.slug, type: "product update", date: item.published_at ? new Intl.DateTimeFormat("en-GB", { dateStyle: "long" }).format(new Date(item.published_at)) : "", title: item.title, summary: item.meta_description || "", details: String(item.body || "").split(/\r?\n/).filter(Boolean), published_at: item.published_at, meta_description: item.meta_description }); else setUpdateError(true); }).catch(() => setUpdateError(true)); }, [slug]); usePageMetadata({ title: update ? `${update.title} | CG Tennis OS™` : "Product update | CG Tennis OS™", description: update?.summary || "Published product progress from CG Tennis OS™.", path: `/changelog/${slug}`, schema: update ? { "@context": "https://schema.org", "@type": "TechArticle", headline: update.title, description: update.summary, datePublished: update.published_at || update.date, author: { "@type": "Person", name: "Caroline Gossage" }, publisher: { "@type": "Organization", name: "CG Tennis OS™", url: SITE_URL }, mainEntityOfPage: `${SITE_URL}/changelog/${slug}` } : undefined }); if (!update) return updateError ? <NotFound /> : <section className="not-found"><p className="eyebrow">Loading product update</p><h1>Finding the latest note.</h1></section>; return <article className="update-page"><header className="narrow article-head"><Link href="/changelog" className="back"><ArrowLeft size={16} /> All changelog entries</Link><p className="eyebrow">Product update</p><h1>{update?.title || "Product update"}</h1><p className="dek">{update?.summary || "Published product progress from CG Tennis OS™."}</p></header><div className="article-body">{(update?.details || ["This update is available in the live content library."]).map(detail => <p key={detail}>{detail}</p>)}<aside className="share-note"><p className="eyebrow">Technical record</p><p>This entry is kept separate from the public coaching Insights library.</p></aside></div></article>; }

export function Overview() { const points = [["The week, in one view.", "Book, track and message from one calendar without chasing your own diary."], ["Every player, more clearly.", "Keep a developing player story close to the next session, not buried in old notes."], ["Notes that keep their meaning.", "Turn the useful thought from court-side into a record you can use later."], ["A calmer parent conversation.", "Share the right update at the right time, with less explaining from memory."]]; return <><section className="overview-hero"><div className="frame two-col"><div><p className="eyebrow">CG Tennis OS™</p><h1>One home for the coaching work <i>that matters.</i></h1></div><div><p>CG Tennis OS™ gives the working parts of a coaching week a place to land, so attention can stay where it belongs: with the player, the plan and the next useful conversation.</p><a href="https://cgtennisos.com/pricing" target="_blank" rel="noreferrer" className="button-primary pricing-cta" aria-label="See CG Tennis OS trial and pricing">See trial and pricing <ArrowUpRight size={17} /></a><small>Trial and pricing live at cgtennisos.com.</small></div></div></section><section className="system-list"><div className="frame"><Mark number="01" label="For the everyday work" /><div>{points.map(([title, text], index) => <a className="system-list-card" key={title} href="https://cgtennisos.com" target="_blank" rel="noreferrer" aria-label={`Open CG Tennis OS for ${title}`}><span>0{index + 1}</span><div><h2>{title}</h2><p>{text}</p></div><CheckIcon /></a>)}</div></div></section><section className="home-close"><div className="frame"><p className="eyebrow peach">A clear first step</p><h2>Make room for the coaching.<br /><i>We will hold the admin.</i></h2><a href="https://cgtennisos.com" target="_blank" rel="noreferrer" className="text-link light-link">Start your free trial <ArrowUpRight size={17} /></a></div></section></>; }
function CheckIcon() { return <span className="check">✓</span>; }
export function Contact() { return <section className="contact"><div className="frame two-col"><div><p className="eyebrow">Contact</p><h1>A conversation can be <i>a useful start.</i></h1></div><div className="contact-card"><Mail size={27} /><p>For CG Tennis OS™, the book, coaching enquiries, or a considered question about the work, email Caroline and the team.</p><a href="mailto:hello@cgtennisacademies.com">hello@cgtennisacademies.com <ArrowUpRight size={18} /></a><span>We read every note.</span></div></div></section>; }
export function NotFound() { return <section className="not-found"><p className="eyebrow">Wrong side of the court</p><h1>This page has moved on.</h1><Link href="/" className="button-primary">Return home</Link></section>; }
